# This is a basic workflow to help you get started with Actions

name: test_dispatch

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [test-dispatch]

jobs:
  generate-docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Create new file
        run: |
          echo "This is a newly generated file." > new_file.txt

      - name: check for changes
        run: |
          git config user.email "badiajustine@gmail.com"
          git config user.name "Justine"
          git add new_file.txt
          if git diff-index --quiet HEAD --; then
            echo "changes_detected=false" >> "$GITHUB_ENV"
          else
            git commit -m "Added new file: new_file.txt on $(date +"%Y-%m-%d")"
            echo "changes_detected=true" >> "$GITHUB_ENV"
          fi

      - name: push changes to main
        if: ${{ env.changes_detected == 'true' }}
        run: git push origin main
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
