# This is a basic workflow to help you get started with Actions

name: test_dispatch

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [test-dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check for changes
        run: echo "changes_detected=true" >> "$GITHUB_ENV"
    
      - name: push changes to main
        if: ${{ env.changes_detected }} == 'true'
        run: echo "coucou"
